pip install numpy
pip install pandas
pip install matplotlib
pip install scipy
pip install scikit-learn
pip install pyecharts
pip install seaborn
pip install plotly
pip install bokeh
pip install pydot
pip install kiwisolver
pip install pyparsing
pip install six
